" Aric's portable vimrc. no vundle sorry :(
filetype off                   
syntax on

set ts=2
set shiftwidth=2
set expandtab
set showmatch

set t_Co=256
set nocompatible              
set scrolloff=99
set shell=bash
set backspace=indent,eol,start
set hlsearch

if has("relativenumber")
  set relativenumber
  noremap <f3> :set relativenumber!<return>
  inoremap <f3> :set relativenumber!<return>
else
  set number
  noremap <f3> :set nonumber!<return>
  inoremap <f3> :set nonumber!<return>
endif

" :nohl to clear

nnoremap <F5> :set invpaste paste?<CR>
set pastetoggle=<F5>
set showmode

noremap <f4>  :set syntax=sh<return>
inoremap <f4> :set syntax=sh<return>
nnoremap Q <nop>

"Visually change lines with ctrl up and down
nnoremap <silent> <C-Up> gk
nnoremap <silent> <C-Down> gj

"Change splits with ctrl left and right
nnoremap <silent> <C-Left> <C-w><C-w>
nnoremap <silent> <C-Right> <C-w><C-w>
