" Aric's portable vimrc. no vundle sorry :(

filetype off                   " required!
syntax on

set t_Co=256
set nocompatible               " be iMproved
set scrolloff=999
set ts=2
set shiftwidth=2
set expandtab
set showmatch
set relativenumber
set shell=bash
set backspace=indent,eol,start


nnoremap <F5> :set invpaste paste?<CR>
set pastetoggle=<F5>
set showmode

noremap <f3> :set relativenumber!<return>
inoremap <f3> :set relativenumber!<return>
noremap <f4>  :set syntax=sh<return>
inoremap <f4> :set syntax=sh<return>
nnoremap Q <nop>
map! ii <Esc> " map ii to Esc
